# Needs to be the same as the root directory
site_name: SparkFun_GNSS_pHAT


# Configures webpage navigation
# Excludes README.md files from being built as webpages
exclude_docs: |
  README.md

nav:
  - index.md
